### ISSUE TITLE
F0修改建议

### ISSUE THREAD

**Issue by pujiaxun** [Daisyyuxi/web_tasks#1]
- 要求是一个HTML文件呀，`基础层面上的网页.txt`是什么意思??? 命名不许用中文，而且必须是html文件
- 建议加点样式什么的吧

**完成的太随意了，我不能用浏览器打开txt文件情况下，可以说这是未完成**

**Comment by Daisyyuxi** [comment]
OK了

**Comment by pujiaxun** [comment]
恩还不错，还有大把时光，再给你点建议
- 显示密码的功能也有了很不错，但是单选框...选了就不能取消，显然是不符合要求的，你可以用复选框。~~最好是用button或者label这类的，通过判断现在的input type来改变，而不是单选框checked。~~后来想想其实就复选框也可以，你喜欢就行。
- JS代码不要直接写在onclick里啊，这真真是最过分的了。。提取成函数放在script标签，或者更建议你放到单独的`.js`文件。onclick里只需要调用函数。
- CSS单独提出来，存成`.css`文件，再用link标签调用
- 输入框是挺跳的，但是选中以后还是会有默认的吃藕的要死的方形边框，可以查查怎么去掉。

**Comment by Daisyyuxi** [comment]
1,3,4都改好了，就那个JS代码老是弄不成功，提取到script标签里就实现不了显示密码的效果了

**Comment by pujiaxun** [comment]
可能是this关键字不是你想要的那个吧
给你个思路，更改input对象的type值，就不需要这么麻烦了
